### ISSUE TITLE
l18n: Support for French (fr) 🇫🇷

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#237]
Translate Wiredash to French.

Unfortunately, we aren't fluent in French and would like a native speaker to help us out.

Please follow the [instructions](https://docs.wiredash.io/sdk/localization/#add-support-for-new-languages) on how to contribute your locale to Wiredash 💙

**Comment by passsy** [comment]
@stefandevo?

**Comment by passsy** [comment]
@huextrat?

**Comment by msitbon** [comment]
hello guys, thanks for your platform that I am exploring :)

I see that this issue is still open but I wonder if someone is already working on it.
I would gladly propose the translations if it is not the case.

By the way, I think some variables might be missing (for example, the confirmation message when the user wants to leave the promoter screen poll).

thx

**Comment by msitbon** [comment]
@passsy https://github.com/wiredashio/wiredash-sdk/pull/255
