### ISSUE TITLE
Keyboard immediately closes with Flutter 3.7 and Router

### ISSUE THREAD

**Issue by percula** [wiredashio/wiredash-sdk#262]
**Describe the bug**
Since updating to Flutter 3.7, there is a bug that immediately closes the on-screen keyboard when trying to type a description. 

See this [sample project](https://github.com/percula/wiredash_test).

This bug only happens with the following criteria:
- Using Flutter 3.7
- Using `MaterialApp.router` with a router package (in my case, `go_router`)

**Stacktrace**
_What's the stacktrace?_
In browsers, check the `Console`.
The stacktrace isn't particularly useful in this situation.

**Wiredash SDK Info**
_Which SDK are you using?_ 1.5.0
_On which platform are you seeing the crash?_ iOS and Android

**Flutter SDK**
_Which Flutter version are you using? Run `flutter doctor -v`_ 3.7

**Screenshots**

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/16809252/216086169-621711f4-49f7-4e1e-a127-5a971b4c53a6.gif)

**Comment by passsy** [comment]
Thanks for reporting. I can reproduce the bug on Android and iOS. It's likely to be a go_router issue, as others have reported the same without `wiredash` https://stackoverflow.com/questions/74682113/flutter-android-app-onbackinvokedcallback-is-not-enabled-for-the-application-s

**Comment by passsy** [comment]
Most likely a bug in flutters `Navigator`.

https://github.com/flutter/flutter/blob/254a796bc3f8a32d3e09c1416bce7b7b9f1ba33b/packages/flutter/lib/src/widgets/navigator.dart#L3526

Wiredash wraps the app with new widgets, causing `NavigatorState.didUpdateWidget` to be called. This is normal.

I assume that `if (oldWidget.pages != widget.pages && !restorePending) {` results to `true`, although `oldWidget.pages == widget.pages`. But the list check is using the `==` comparison, not `ListEquality` to check for the content.
This causes the navigator to `_updatePages()` resulting in the Navigator requesting focus. This might be the second bug, because the Navigator is requesting focus although it doesn't have focus.

Open questions:
- Why is the behaviour different from 3.0?
- Why does this not happen without go_router?

**Comment by percula** [comment]
Yeah, I agree, this is probably a bug in flutter's `Navigator`. It was working in Flutter 3.3, so something between 3.3 and 3.7 caused this regression.

**Comment by Prayer-RecycleSmart** [comment]
Same here

**Comment by percula** [comment]
For anyone looking for a temporary fix, simply stay on the stable channel (3.7.0 or 3.7.1) and replace `app.dart` in your Flutter SDK directory with [this](https://gist.github.com/percula/53931260f13d2d34512e30ee37e8d835). Then run `flutter doctor -v` and you're all set until the fix gets rolled into a stable flutter version.

**Comment by passsy** [comment]
The [bug I discovered](https://github.com/wiredashio/wiredash-sdk/issues/262#issuecomment-1412468346) where `_updatePages()` is unnecessarily called is not a bug in Flutter but in your example code.

The router is defined in a `StatelessWidget`. This causes the router to completely rebuild because go_router generates a `routerKey` forcing the widget to lose state. Therefore it is ok to call `_updatePages()`.

https://github.com/percula/wiredash_test/blob/363dc4024fc2b95b8c084818cbfc9bc3f7299c48/lib/main.dart#L9-L20

Use a `StatefullWidget` instead and keep the same `_router` instance. Then the same issue persists but it has a different cause as described in https://github.com/flutter/flutter/issues/119849

**Comment by percula** [comment]
Ah, yeah, I should have made that a `StatefulWidget`, good catch!

**Comment by cliftonlabrum** [comment]
@percula Thank you for providing a workaround. This is a nasty, show-stopping bug. 😅 I have looked through my `/flutter` folder and I don't see an `app.dart` anywhere. Which subfolder is that in?

**Comment by cliftonlabrum** [comment]
I found it: `flutter/packages/flutter/lib/src/material/app.dart`

but after running `flutter doctor -v`, all my instances of `MaterialApp` have `Undefined name MaterialApp` errors on them. 🤔

**Comment by percula** [comment]
> 

Hmm, try `flutter clean`? Seems like some cache needs to be cleared and recreated.

**Comment by passsy** [comment]
Please upgrade to Wiredash `1.6.0` to fix it.

And thanks again for reporting!
