### ISSUE TITLE
Unable to login into the wiredash console

### ISSUE THREAD

**Issue by Udhay-Adithya** [wiredashio/wiredash-sdk#372]
**Describe the bug**
Unable to login into the wiredash website/wiredash console(https://wiredash.com/). I have tried all the login methods everything gives me an error.

**Stacktrace**
[Error] Failed to load resource: the server responded with a status of 404 () (3w7zQ0eb_400x400.jpg, line 0)
[Error] Could not connect to the server.
[Error] Fetch API cannot load https://api.wiredash.io/users/checkMember due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (checkMember, line 0)
[Error] FetchError: [POST] "https://api.wiredash.io/users/checkMember": <no response> Load failed

**Wiredash SDK Info**
https://wiredash.com/
Macbook Air M2  - Safari(Version 18.1.1 (20619.2.8.11.12))

**Screenshots**
<img width="404" alt="Untitled" src="https://github.com/user-attachments/assets/53214c11-58f0-49d3-8fd7-40b4aff96420">
It just keeps loading forever

**Comment by passsy** [comment]
Hey @Udhay-Adithya, thanks for reaching out.

I found the error in our logs. I can assure you the 404 request is not the issue.

I guess the request to `https://api.wiredash.io/users/checkMember` fails because before doing the `POST` request, your browser does a pre-flight check to validate the cors headers.


From the logs I see `HEAD` and `GET` requests to `https://api.wiredash.io/users/checkMember` which are not supported, thus returning `405`. Because they error, your browser does not try the `POST` request.
The odd thing is: browsers usually use an `OPTIONS` request to do that, not `HEAD` or `GET`.

I could not reproduce this in Safari myself. It might be caused by a browser plugin.

Can you try to figure out (using the Safari Web Inspector) where those requests originate?
Do you see the same behavior in another browser?

**Comment by Udhay-Adithya** [comment]
Hi @passsy,

Thank you for your prompt response and assistance.

Upon further investigation, I discovered that the issue was caused by my university's Wi-Fi network, which seems to block access to certain endpoints, including those used by Wiredash. I tested the login functionality on a different network, and it worked perfectly.

There is no issue with Wiredash itself. Thank you again for looking into this!
