### ISSUE TITLE
Can i Get User Mobile Information??

### ISSUE THREAD

**Issue by sagarshende23** [wiredashio/wiredash-sdk#59]
If a user tries to submit their Bugs or App Problem then I Need a Mobile Information Following As:-
1.Time

2.Device Name (Ex:- RMX1911)

3.Model

4.Brand

4.SDK version

5.Android Version

If Your Give consent To share this Information, Because it helps Developer Like me Solve their Problem as Quick as Possible

Below is the Image for Google getting some Information About Mobile When user want to Submit an issue.

![Screenshot_2020-07-01-07-57-22-11](https://user-images.githubusercontent.com/43273993/86197715-9bef3600-bb73-11ea-8695-981d5633c107.jpg)
![Screenshot_2020-07-01-07-57-51-11](https://user-images.githubusercontent.com/43273993/86197723-a0b3ea00-bb73-11ea-9258-58eafa1da494.jpg)
![Screenshot_2020-07-01-07-57-37-21](https://user-images.githubusercontent.com/43273993/86197727-a3164400-bb73-11ea-87fb-63c9c0d22a51.jpg)

**Comment by flschweiger** [comment]
Thanks for your feedback! Currently Wiredash is just using Flutter-specific data, e.g. Flutter version, screen size, OS, etc. because we wan't to keep the native dependencies as low as possible. However, this would be a nice idea for a plugin package that can be dropped into the project in addition to the default wiredash package 🙂

**Comment by sagarshende23** [comment]
Thanks for considering it 😀😀

**Comment by flschweiger** [comment]
@passsy I think this is something we could consider adding through a plugin package 💭

**Comment by ciriousjoker** [comment]
Isn't this long fixed since there's `collectMetadata` now?
