### ISSUE TITLE
Custom feedback data

### ISSUE THREAD

**Issue by aseef17** [wiredashio/wiredash-sdk#76]
Is there any support planned for custom data to be passed through feedback.

I'll explain the current situation where we need this.
We are building a small e-commerce application and would ideally want to just have one wire dash project.
Now, there are 2 mobile applications - User and Driver. We would want to use the same project to gather feedback for both the applications during alpha/beta testing. 

Let us know if there's anyway where we can segregate the feedback (I know that tags is a way to do this but that'll require us to manually tag every feedback. We would prefer if we can either set the tag programatically or pass custom parameters in the feedback)

**Comment by brianegan-wiredash** [comment]
Thanks so much for the feedback! This is a great idea. 

As a heads up, we're making some big improvements to the Wiredash console, including the ability to make your own custom tags! Once that is in place, we'll add support to the Flutter side to tag feedbacks with them!

**Comment by gabeschine** [comment]
What do you think about custom fields with arbitrary (string?) values?

As an example, I want to include a) the model of the phone making a bug report, b) some identifying information about the dataset they are using.

For (a), on Android, this can make a huge difference because of the variance in system software from different phone makers, and for (b) it can help reproduce the bug.

**Comment by kutear** [comment]
and i want to upload some file of local log， it's possible to export `Request` to developer?

**Comment by passsy** [comment]
With Wiredash 1.0.0 you can add custom metadata to your feedback.

Checkout the official documentation: https://docs.wiredash.io/sdk/custom-properties/
